### ISSUE TITLE
Incorrect Calculations and Unit Quaternion

### ISSUE THREAD

**Issue by josephcantrell14** [vakrilov/native-script-accelerometer#10]
The NativeScript-Accelerometer-Advanced plugin is coded incorrectly. Calculating the unit quaternion value q0 is not necessary as it is provided by the sensor on newer devices using event.values[3] for TYPE_ROTATION_VECTOR. Dividing by gravity (9.81 m/s^2) is not necessary as it is not included in the sensors used. Try this code to improve: 

wrappedCallback({
                **values: event.values,**
                x: event.values[0],
                y: event.values[1],
                z: event.values[2],

**Comment by progyadeep** [comment]
@josephcantrell14 I noticed an issue on my Moto G6 plus (Android 9.0): even if I place the device on the ground, I get different coordinate values after every update iteration. For now, I'm using rounded off values and it has improved the situation a little bit, but it still isn't 100% legit altogether.

**Comment by vakrilov** [comment]
Hey @josephcantrell14 
Not sure If I understand completely your remarks. I've tried to keep the API and reported values consistent for IOS and Android and that is why I do the `divide by gravity` calculation on android.

However, If you think there is room for extending the data or the API with additional useful info - a PR will be more than welcome.
