### ISSUE TITLE
How can I get Phone direction

### ISSUE THREAD

**Issue by poorcoder** [vakrilov/native-script-accelerometer#2]
Hi Vakrilov...

I am trying to develop a map app with native script...

I am using https://github.com/dapriett/nativescript-google-maps-sdk to create google map on app page... everything goes well at map...

But my problem is when a user moves around the phone ( like he is standing up and turns his self around ) I want to change map direction...
At the plugin there is bearing property if I manually update that value map is turning as I need but I need to detect the app sensor to user movements to update bearing value...

Pls give me a direction how can I do this...
Thanks.

**Comment by vakrilov** [comment]
Hi,
I don't think using the accelerometer the right way to do that. Here is why:
The accelerometer sensor _"measures the acceleration force in m/s2 that is applied to a device on all three physical axes (x, y, and z), including the force of gravity"_. So, it is good for detection motion detection - stuff like shake, tilt or determining the direction of the gravity. It not so good for detecting the orientation of the device relative to Earth direction. More info [here](https://developer.android.com/guide/topics/sensors/sensors_overview.html#sensors-intro).

It seems to me that you actually need a compass sensor to do that.

Also it's worth checking out if there is some build-in API in the google maps SDK that will automatically orient the map for you.
