### ISSUE TITLE
How can i stop accelerometer updates ?

### ISSUE THREAD

**Issue by memePushpendu** [vakrilov/native-script-accelerometer#6]
Well actually i am able to stop it using stopaccelerometerupdates() function but after that when i am going to start the accelerometer again it throws error : 
Currently not listening for accelerometer events.

**Comment by vakrilov** [comment]
That is strange. By examining the code - it looks to me that the `Currently not listening for acceleration events.` error is only thrown is the `stopAccelerometerUpdates()` method for [android](https://github.com/vakrilov/native-script-accelerometer/blob/master/index.android.ts#L82) and [ios](https://github.com/vakrilov/native-script-accelerometer/blob/master/index.ios.ts#L59). I guess that you can get the exception if you call the stop method twice though. Can you check if this is the case in your app?

**Comment by memePushpendu** [comment]
It's some kind of logical issue by me I guess. When I first open the app the accelerometer starts updating and after that when I minimise the app and open it again it throws the error as the accelerometer is already updating but I am trying to initialise it again. Let me find the solution and I ll give an update.

_Sent from my Lenovo A6020a46 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by progyadeep** [comment]
@vakrilov This issue faced by @memePushpendu can be solved if the package comes with a flag variable like `isAccelerometerUpdateOn` that will check if the accelerometer is already updating the values. Or, using a JS workaround, @memePushpendu can simply stop the accelerometer updates process once the `xml` page goes out of focus.

**Comment by vakrilov** [comment]
Hey @progyadeep - I still think `stopAccelerometerUpdates` is the right way to do it. Now that I look at it again - I think it might be better if the method does not throw exception if the listener was not started.

**Comment by progyadeep** [comment]
The issue pops up when `startAccelerometerUpdates()` is invoked while it's already in process. Whenever the method is called, it should stop any existing instance and then (re)start the process. That way, I think, the exception throwing scenario will altogether be eliminated.

**Comment by vakrilov** [comment]
Hey @progyadeep - I have implemented you suggestion and published `nativescript-accelerometer@3.0.0` along with some other improvements.
