### ISSUE TITLE
Error: Could not get foregroundActivity.

### ISSUE THREAD

**Issue by damain** [vakrilov/native-script-accelerometer#7]
Hi I am trying to use this plugin in nativescript-vue on the landing page for the app and I get the following error 
```"Error: Could not get foregroundActivity."```

this could be from index.android.ts on line 23
```
var activity = application.android.foregroundActivity;
    if (!activity) {
        throw Error("Could not get foregroundActivity.");
    }
```

From my reading it looks like foregroundActivity is only available after navigatedTo is called.

**Comment by carrbrpoa** [comment]
Hey @damain did you solve this? I'm getting this error when trying to run from background worker.

**Comment by damain** [comment]
@carrbrpoa no I didn't find a solution.

**Comment by stanimirsp5** [comment]
Same error. Works on iOS but it doesn`t on Android

**Comment by stanimirsp5** [comment]
the problem is that  application.android.foregroundActivity is undefined. You must wait to load. Easy way is to use setTimeout()

`
setTimeout(() => {
     accelerometer.startAccelerometerUpdates(function(data) {

         console.log("x: " + data.x + "y: " + data.y + "z: " + data.z);
     }, { sensorDelay: "ui" });
    }, 2000);
`

**Comment by vakrilov** [comment]
I have changed the implementation in `nativescript-accelerometer@3.0.0` to get the application context instead of foreground activity. Generally the app context is available earlier and should be accessible form workers too.
